#!/bin/sh

echo "Switching to develop branch (usually should be no-op)..."
git stash
git checkout develop

echo "Building site..."
stack exec site clean
stack exec site build

echo "Pulling from master..."
git fetch --all
git checkout -b master --track origin/master

echo "Copying site files..."
cp -a _site/. .

echo "Committing..."
git add -A
echo "Commit number: $(date +%s)"
git commit -m "Publish $(date +%s)"

echo "Pushing to origin..."
git push origin master:master

echo "OK, returning to develop"
git checkout develop
git branch -D master
git stash pop
